Ppdates to match latest EVM market maker API changes
DFlowProtocol/market-maker-api-spec pull request #1
Opened 2023-11-21 21:19 UTC by mitch-dflow

2023-11-23 17:13 UTC, jeff-delonge requested changes

2023-11-23 17:13 UTC, jeff-delonge commented on spec/EvmLegacy.yml
> +          description: oken units sent to retail trader per token received from retail trader. Must be greater than or equal to the minFillPrice.
Fix typo

2023-11-23 17:13 UTC, jeff-delonge commented on spec/EvmLegacy.yml
Rename `EvmStandard.yml`, rename "EVM Standard Swaps"

2023-11-23 17:13 UTC, jeff-delonge commented on spec/EvmLegacy.yml
>          rfqOrderSignature:
Fix field name

2023-11-23 17:18 UTC, jeff-delonge commented on spec/EvmLegacy.yml
> +          description: Send quantity specified as a scaled integer. This is the `takerAmount` to use when constructing the DFlow Swap order.
The descriptions aren't using backticks around field names consistently. We should be consistent and either use backticks in all or none of the descriptions

2023-11-24 13:39 UTC, mitch-dflow commented on spec/EvmLegacy.yml
> +          description: Send quantity specified as a scaled integer. This is the `takerAmount` to use when constructing the DFlow Swap order.
the issue I found is that you can't use a backtick to start a string field so if it was at the start it was causing problems. I'll remove them all

2023-11-24 15:49 UTC, jeff-delonge approved these changes

2023-11-24 15:49 UTC, merged